"""
Validate the raw WRDS dataset and write a data-quality report.

Checks are grouped as
  FAIL  - structural problems that would invalidate research (exit code 1),
  NOTE  - known, explained data features that downstream code must handle,
  PASS  - everything else.

Usage:
    python scripts/02_validate_data.py [--raw data/raw] [--report reports/data_validation.md]
"""
import argparse
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
FAR_FUTURE = pd.Timestamp("2099-12-31")

KEYS = {
    "sp500_membership": ["permno", "mbrstartdt"],
    "crsp_monthly": ["permno", "mthcaldt"],
    "crsp_stocknames": ["permno", "namedt"],
    "ccm_link": ["gvkey", "permno", "linkdt"],
    "comp_gics_history": ["gvkey", "indfrom"],
    "comp_company": ["gvkey"],
    "comp_funda": ["gvkey", "datadate"],
    "ff5_factors_monthly": ["date"],
    "ff5_factors_daily": ["date"],
    "ff_reversal_monthly": ["date"],
    "sp500_index_daily": ["date"],
    "spy_daily": ["date"],
    "spmo_daily": ["date"],
}
SPELLS = {  # table -> (entity, start, end)
    "sp500_membership": ("permno", "mbrstartdt", "mbrenddt"),
    "ccm_link": ("permno", "linkdt", "linkenddt"),
    "comp_gics_history": ("gvkey", "indfrom", "indthru"),
}


class Report:
    def __init__(self):
        self.rows, self.sections = [], []

    def check(self, name, status, result):
        self.rows.append((name, status, result))

    def section(self, title, body):
        self.sections.append(f"### {title}\n\n{body}\n")

    @property
    def failed(self):
        return any(s == "FAIL" for _, s, _ in self.rows)

    def markdown(self, manifest):
        p = manifest["params"]
        lines = [
            "# Data validation report", "",
            f"Generated by `scripts/02_validate_data.py` for the WRDS pull of {manifest['pulled_at'][:10]} "
            f"(prices {p['start']} to {p['end']}, universe = S&P 500 members on or after {p['universe_from']}).", "",
            "| Check | Status | Result |", "|---|---|---|",
            *[f"| {n} | {s} | {r} |" for n, s, r in self.rows], "",
            "## Details", "", *self.sections,
        ]
        return "\n".join(lines)


def md_table(df, floatfmt="{:.3f}"):
    def fmt(v):
        if isinstance(v, pd.Timestamp):
            return str(v.date())
        if isinstance(v, float):
            return floatfmt.format(v)
        return "" if pd.isna(v) else str(v)
    head = "| " + " | ".join(map(str, df.columns)) + " |"
    sep = "|" + "---|" * len(df.columns)
    body = ["| " + " | ".join(fmt(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join([head, sep, *body])


def overlaps(df, entity, start, end):
    d = df.assign(_end=df[end].fillna(FAR_FUTURE)).sort_values([entity, start])
    return int((d.groupby(entity)[start].shift(-1) <= d["_end"]).sum())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--raw", type=Path, default=ROOT / "data" / "raw")
    ap.add_argument("--report", type=Path, default=ROOT / "reports" / "data_validation.md")
    args = ap.parse_args()
    raw, rep = args.raw, Report()

    manifest = json.loads((raw / "MANIFEST.json").read_text(encoding="utf-8"))
    ds = manifest["datasets"]
    T = {name: pd.read_parquet(raw / f"{name}.parquet") for name in KEYS}
    years = sorted(int(p.stem) for p in (raw / "crsp_daily").glob("*.parquet"))
    daily = pd.concat([pd.read_parquet(raw / "crsp_daily" / f"{y}.parquet",
                                       columns=["permno", "dlycaldt", "dlyret", "dlyretx", "dlyprc", "dlyprcflg"])
                       for y in years], ignore_index=True)
    m, mb = T["crsp_monthly"], T["sp500_membership"]
    start, end = pd.Timestamp(manifest["params"]["start"]), pd.Timestamp(manifest["params"]["end"])

    # ---- 1. completeness against MANIFEST ----
    bad = [n for n in KEYS if ds[n]["rows"] != len(T[n])]
    exp_years = list(range(start.year, end.year + 1))
    daily_rows = daily.groupby(daily.dlycaldt.dt.year).size()
    bad += [f"crsp_daily/{y}" for y in exp_years
            if y not in years or ds["crsp_daily"]["rows"].get(str(y)) != daily_rows.get(y)]
    rep.check("Row counts match MANIFEST", "FAIL" if bad else "PASS",
              f"mismatch: {', '.join(bad)}" if bad else f"{len(KEYS)} tables + {len(years)} daily files")

    # ---- 2. primary keys ----
    dups = {n: int(T[n].duplicated(k).sum()) for n, k in KEYS.items()}
    dups["crsp_daily"] = int(daily.duplicated(["permno", "dlycaldt"]).sum())
    bad = {n: v for n, v in dups.items() if v}
    rep.check("Primary keys unique", "FAIL" if bad else "PASS", str(bad) if bad else "0 duplicates in all tables")

    # ---- 3. validity intervals ----
    res = {n: (int((T[n][s] > T[n][e]).sum()), overlaps(T[n], ent, s, e)) for n, (ent, s, e) in SPELLS.items()}
    bad = {n: v for n, v in res.items() if any(v)}
    rep.check("Date intervals valid and non-overlapping", "FAIL" if bad else "PASS",
              f"(start>end, overlaps): {bad}" if bad else "membership, CCM links, GICS history")

    # ---- 4. trading calendars ----
    cal = set(T["sp500_index_daily"].date)
    diffs = {"crsp_daily": set(daily.dlycaldt.unique()) ^ cal, "ff5_factors_daily": set(T["ff5_factors_daily"].date) ^ cal}
    for etf in ("spy_daily", "spmo_daily"):
        d = T[etf].date
        diffs[etf] = {x for x in cal if d.min() <= x <= d.max()} ^ set(d)
    bad = {n: len(v) for n, v in diffs.items() if v}
    rep.check("Trading calendars aligned", "FAIL" if bad else "PASS",
              f"days differing from index calendar: {bad}" if bad else
              f"{len(cal):,} days; stocks, FF factors, SPY and SPMO identical to index calendar")

    # ---- 5. universe ----
    univ = set(mb.loc[mb.mbrenddt >= pd.Timestamp(manifest["params"]["universe_from"]), "permno"])
    missing = univ - set(m.permno)
    rep.check("Every universe PERMNO has CRSP data", "FAIL" if missing else "PASS",
              f"missing: {sorted(missing)[:10]}" if missing else f"{len(univ):,} PERMNOs")

    month_ends = np.sort(m.mthcaldt.drop_duplicates().to_numpy())
    is_member = (mb.mbrstartdt.values[:, None] <= month_ends) & (mb.mbrenddt.values[:, None] >= month_ends)
    n_members = is_member.sum(axis=0)
    out = month_ends[(n_members < 495) | (n_members > 510)]
    rep.check("Constituents per month-end within [495, 510]", "FAIL" if len(out) else "PASS",
              f"range {n_members.min()}-{n_members.max()} over {len(month_ends)} months"
              + (f"; out of range: {len(out)}" if len(out) else ""))

    # member-month panel: one row per (permno, month-end) in the index, built from the constituent
    # list (not from CRSP) so that members without any CRSP record are counted too
    spell, month = np.nonzero(is_member)
    pm = (pd.DataFrame({"permno": mb.permno.to_numpy()[spell], "mthcaldt": month_ends[month]})
            .merge(m, on=["permno", "mthcaldt"], how="left"))
    no_ret = pm[pm.mthret.isna()].assign(
        reason=lambda x: x.mthretflg.map({"NT": "not trading (NT)"}).fillna("no CRSP record yet"),
        ticker=lambda x: x.permno.map(m.groupby("permno").ticker.last()))
    rep.check("Member-months with a monthly return", "NOTE" if len(no_ret) else "PASS",
              f"{1 - len(no_ret) / len(pm):.4%} of {len(pm):,}; {len(no_ret)} missing (see details)")
    if len(no_ret):
        tbl = (no_ret.groupby(["permno", "ticker", "reason"], dropna=False)
                     .agg(months=("mthcaldt", "size"), first=("mthcaldt", "min"), last=("mthcaldt", "max"))
                     .reset_index().sort_values("first"))
        rep.section("Member-months without a return",
                    "Returns are missing in CRSP itself: either the stock was not trading (e.g. Mattel's "
                    "1974-75 suspension) or it joined the index before its first CRSP month (e.g. the AT&T "
                    "divestiture companies, members from Dec-1983 but trading from Feb-1984). Treat these "
                    "member-months as untradeable.\n\n" + md_table(tbl))

    # ---- 6. monthly vs compounded daily returns ----
    d = daily.dropna(subset=["dlyret"]).assign(month=lambda x: x.dlycaldt.dt.to_period("M"),
                                               gross=lambda x: 1 + x.dlyret.astype(float))
    comp = d.groupby(["permno", "month"]).gross.prod().sub(1).rename("compounded").reset_index()
    mm = m.dropna(subset=["mthret"]).assign(month=lambda x: x.mthcaldt.dt.to_period("M"))
    j = mm[["permno", "month", "mthret", "mthdelflg"]].merge(comp, on=["permno", "month"])
    j["diff"] = (j.mthret.astype(float) - j.compounded).abs()
    big = j[j["diff"] > 1e-4]
    unexplained = big[big.mthdelflg == "N"]
    rep.check("Monthly return = compounded daily returns (1bp)", "NOTE" if len(big) else "PASS",
              f"{len(j):,} security-months; {len(big)} differ, {len(big) - len(unexplained)} of them in "
              f"delisting months (monthly includes the delisting return), {len(unexplained)} other")
    if len(unexplained):
        rep.section("Monthly/daily return differences outside delisting months",
                    unexplained[["permno", "month", "mthret", "compounded", "diff"]]
                    .sort_values("diff", ascending=False).head(20).pipe(md_table, "{:.4f}"))

    # ---- 7. value sanity ----
    lt_m1 = int((daily.dlyret < -1).sum())
    rep.check("Daily returns >= -100%", "FAIL" if lt_m1 else "PASS", f"{lt_m1} violations")
    gt1 = daily[daily.dlyret > 1]
    rep.check("Daily returns > +100%", "NOTE" if len(gt1) else "PASS",
              f"{len(gt1)} obs (price flags {gt1.dlyprcflg.value_counts().to_dict()}), mostly low-priced stocks "
              "and the 2020-21 squeezes. Kept as reported; winsorise signals, not returns")
    zero = daily[daily.dlyprc == 0]
    rep.check("Zero daily prices", "NOTE" if len(zero) else "PASS",
              f"{len(zero)} obs, flags {zero.dlyprcflg.value_counts().to_dict()}, market cap null; treat price as missing")

    # ---- 8. identifier and classification coverage of member-months ----
    cl = T["ccm_link"].assign(prio=lambda x: x.linkprim.map({"P": 0, "C": 1, "J": 2}))
    lk = pm[["permno", "mthcaldt", "siccd"]].merge(cl[["permno", "gvkey", "linkdt", "linkenddt", "prio"]], on="permno")
    lk = lk[(lk.mthcaldt >= lk.linkdt) & (lk.mthcaldt <= lk.linkenddt.fillna(FAR_FUTURE))]
    lk = lk.sort_values("prio").drop_duplicates(["permno", "mthcaldt"])
    gh = lk.merge(T["comp_gics_history"][["gvkey", "gsector", "indfrom", "indthru"]], on="gvkey")
    gh = gh[(gh.mthcaldt >= gh.indfrom) & (gh.mthcaldt <= gh.indthru.fillna(FAR_FUTURE))].drop_duplicates(["permno", "mthcaldt"])
    hdr = lk.merge(T["comp_company"][["gvkey", "gsector"]], on="gvkey").dropna(subset=["gsector"])

    f = T["comp_funda"]
    se = f["seq"].fillna(f["ceq"] + f["pstk"]).fillna(f["at"] - f["lt"])
    ps = f["pstkrv"].fillna(f["pstkl"]).fillna(f["pstk"]).fillna(0)
    be = (f.assign(be=se + f["txditc"].fillna(0) - ps, fy=f.datadate.dt.year).dropna(subset=["be"])
           .sort_values("datadate").drop_duplicates(["gvkey", "fy"], keep="last"))
    # Fama-French timing: fiscal year ending in calendar year t-1 is used from July t to June t+1
    lk["fy"] = lk.mthcaldt.dt.year - 1 - (lk.mthcaldt.dt.month < 7).astype(int)
    bm = lk.merge(be[["gvkey", "fy", "be"]], on=["gvkey", "fy"])

    key = ["permno", "mthcaldt"]
    cov = pd.DataFrame({"member_months": pm.groupby(pm.mthcaldt.dt.year // 10 * 10).size()})
    for col, df in [("ccm_link", lk), ("gics_history", gh),
                    ("gics_history_or_header", pd.concat([gh[key], hdr[key]]).drop_duplicates()),
                    ("sic", pm.dropna(subset=["siccd"])), ("book_equity", bm)]:
        cov[col] = df.groupby(df.mthcaldt.dt.year // 10 * 10).size() / cov.member_months
    cov = cov.fillna(0.0)
    cov.index = [f"{d}s" for d in cov.index]
    unlinked = pm.merge(lk[key], on=key, how="left", indicator=True).query("_merge == 'left_only'")
    by_permno = unlinked.groupby("permno").size().sort_values(ascending=False)
    tickers = m.groupby("permno").ticker.last()
    largest = ", ".join(f"{tickers.get(p, p)} ({n})" for p, n in by_permno.head(4).items())
    rep.check("CCM link coverage of member-months", "NOTE" if len(unlinked) else "PASS",
              f"{len(lk) / len(pm):.2%}; {len(unlinked)} unlinked across {len(by_permno)} PERMNOs. "
              f"Largest gaps: {largest}; {int((by_permno <= 2).sum())} PERMNOs miss only 1-2 months")
    rep.check("GICS coverage of member-months", "NOTE",
              f"history table starts 1999-06; with company-header fallback {cov.gics_history_or_header.min():.1%} "
              f"(worst decade) to {cov.gics_history_or_header.max():.1%}; CRSP SIC {cov.sic.min():.1%} in every decade")
    rep.check("Book-equity coverage of member-months", "PASS" if cov.book_equity.min() > 0.98 else "NOTE",
              f"{cov.book_equity.min():.1%}+ in every decade; {int((f.curcd != 'USD').sum())} non-USD "
              f"annual reports ({', '.join(sorted(set(f.curcd.dropna()) - {'USD'}))})")
    rep.section("Coverage of S&P 500 member-months by decade",
                "Book equity follows Fama-French timing (fiscal year ending in t-1 used from July t). "
                "Pre-1999 GICS comes from the Compustat company header, which is backfilled; use CRSP SIC "
                "where it is missing.\n\n" + md_table(cov.rename_axis("decade").reset_index()))

    # ---- 9. factors and benchmarks ----
    ff_d, ff_m = T["ff5_factors_daily"], T["ff5_factors_monthly"]
    na = int(ff_d.isna().sum().sum() + ff_m.isna().sum().sum())
    c = (np.log1p(ff_d[["mktrf", "rf"]].astype(float)).groupby(ff_d.date.dt.to_period("M")).sum().pipe(np.expm1))
    gap = (c.mktrf - ff_m.set_index(ff_m.date.dt.to_period("M")).mktrf.astype(float)).abs().max()
    rep.check("Fama-French factors complete and consistent", "FAIL" if na else "PASS",
              f"{na} nulls; daily-compounded vs monthly Mkt-RF max gap {gap:.4f} (rounding). "
              "Monthly dates are month-start: join on year-month")
    rev = T["ff_reversal_monthly"]
    na = int(rev.isna().sum().sum())
    missing = sorted(set(ff_m.date) ^ set(rev.date))
    rep.check("Reversal factors complete and aligned", "FAIL" if na or missing else "PASS",
              f"{na} nulls; {len(missing)} months differ from the Fama-French monthly table "
              f"({rev.date.min().date()} to {rev.date.max().date()}). French library, downloaded "
              f"{ds['ff_reversal_monthly']['pulled_at'][:10]}")
    idx = T["sp500_index_daily"].set_index("date")
    for etf in ("spy_daily", "spmo_daily"):
        x = T[etf].sort_values("date")
        implied = x.dlyprc.astype(float).pct_change()
        mism = int(((implied - x.dlyretx.astype(float)).abs() > 0.01).sum())
        corr = x.set_index("date").dlyret.astype(float).corr(idx.vwretd.astype(float))
        rep.check(f"{etf.split('_')[0].upper()} prices consistent with returns", "FAIL" if mism else "PASS",
                  f"{x.date.min().date()} to {x.date.max().date()}, {len(x):,} days; {mism} unexplained "
                  f"price jumps; corr with S&P 500 = {corr:.3f}")

    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(rep.markdown(manifest), encoding="utf-8")
    for n, s, r in rep.rows:
        print(f"[{s:4s}] {n}: {r}")
    print(f"Report -> {args.report}")
    sys.exit(1 if rep.failed else 0)


if __name__ == "__main__":
    main()
